### ISSUE TITLE
能否支持与Spring容器的集成呢？

### ISSUE THREAD

**Issue by yijianbo** [threefish/nutz-sqltpl#1]
我看到文档中只写了与Nutz框架的集成，作为一个使用Spring容器，在ORM框架上又特别中意Nutz的人来说，也有非常强烈的需求使用SQLTPL进行扩展，例如Phoenix等新型数据库Nutz的支持力度就不够，如果能有Sqltpl就是一个非常好的补充了。
所以看看能否支持Sqltpl与spring的集成呀？

**Comment by threefish** [comment]
@yijianbo 周末我看看如何集成

**Comment by threefish** [comment]
实现方式的demo我写好了，待我抽空再重构下，上生产，可以先关注下 https://gitee.com/threefish/spring-boot-sqltpl

**Comment by threefish** [comment]
`
 <dependency>
            <groupId>com.github.threefish</groupId>
            <artifactId>sql-tpl</artifactId>
            <version>1.0.1.RELEASE</version>
        </dependency>
`
已可用
