### ISSUE TITLE
没有给预编译参数赋值 确定能用吗？

### ISSUE THREAD

**Issue by readwall** [threefish/nutz-sqltpl#3]
default Sql getSql(String id, NutMap param, Cnd cnd, SqlCallback callback) {
        Sql sql = Sqls.create(getSqlsTplHolder().getSql(id, param));
        sql.setCallback(callback);
        if (cnd != null) {
            sql.setCondition(cnd);
        }
        return sql;
    }

并没有 sql.params().set(name,value)

预编译参数@name 这样的地方没法执行吧

**Comment by threefish** [comment]
@readwall 没有执行sql前，应该没有问题。你可以测试下

**Comment by readwall** [comment]
> @readwall 没有执行sql前，应该没有问题。你可以测试下

那应该没问题 谢谢
